### ISSUE TITLE
How do I check Docker CLI version included PR or not.

### ISSUE THREAD

**Issue by masayuki14** [docker/compose-on-kubernetes#106]
Now I am trying to use Compose On Kubernetes on GKE with as follows.

> **Important**: You will need a custom build of Docker CLI to deploy stacks onto GKE. The build must include [this PR](https://github.com/docker/cli/pull/1583) which has been merged onto the master branch.

But I'm not sure convinced the right Docker CLI version of local machine.
How Do I check it.

Thank you for the developer Team.

**Comment by silvin-lubecki** [comment]
Unless you build and use your own docker/cli, this PR will be shipped only in the next docker/cli release `19.03` (which will be pretty soon). All previous releases (last one is `18.09`) are not compatible with GKE.

**Comment by silvin-lubecki** [comment]
I will now close this issue, hopping my previous comment has enough informations to answer the question. Feel free to re-open the issue if you think I'm wrong 👍

**Comment by masayuki14** [comment]
@silvin-lubecki 
Thank you very much.

Should I add this information to document(`install-on-gke.md`) by PR ?
OR does it not need as `19.03` will ship soon ?

**Comment by silvin-lubecki** [comment]
I think it's not needed as the release will be in few days 👍
