### ISSUE TITLE
How to uninstall / remove?

### ISSUE THREAD

**Issue by bgehman** [docker/compose-on-kubernetes#107]
I'm running docker-desktop (on Mac) `v2.0.4.1 (34207)` from the edge channel.

I'd like use Kubernetes, but without this Compose integration that is automatically installed along with Kubernetes.  I suspect this is the cause of High CPU usage of the hyperkit VM but I can't prove it.  I notice in the kube-apiserver logs these types of things (every minute):

```
I0530 18:49:45.353416       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.compose.docker.com
I0530 18:49:45.973085       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta2.compose.docker.com
I0530 18:49:46.613462       1 controller.go:107] OpenAPI AggregationController: Processing item v1alpha3.compose.docker.com
```

So question: is there a way to have just Kubernetes without the Compose integration in docker-desktop community edition?  I tried deleting the `docker` namespace and that didn't help (the namespace gets stuck in `Terminating` state).  Deleting the namespace showed these errors in kube-apiserver logs (every minute):

```
I0530 18:52:46.620395       1 controller.go:107] OpenAPI AggregationController: Processing item v1alpha3.compose.docker.com
W0530 18:52:46.620493       1 handler_proxy.go:89] no RequestInfo found in the context
E0530 18:52:46.620538       1 controller.go:114] loading OpenAPI spec for "v1alpha3.compose.docker.com" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0530 18:52:46.620550       1 controller.go:127] OpenAPI AggregationController: action for item v1alpha3.compose.docker.com: Rate Limited Requeue.
```

with continuing high cpu usage for the hyperkit VM...

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
