### ISSUE TITLE
I can not deploy to GKE  with "failed to find a Stack API version"

### ISSUE THREAD

**Issue by masayuki14** [docker/compose-on-kubernetes#108]
I tryed to install with Document as follows:
https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-gke.md
But I couldn't run compose-on-kubernetes with GKE.

So I run installing process 2 times. But I can't.
These are commands I executed 2nd time.

```
% kubectl create namespace compose
Error from server (AlreadyExists): namespaces "compose" already exists

% kubectl -n kube-system create serviceaccount tiller
Error from server (AlreadyExists): serviceaccounts "tiller" already exists

% kubectl -n kube-system create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount kube-system:tiller
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "tiller" already exists

% helm init --service-account tiller
$HELM_HOME has been configured at /Users/masayuki14/.helm.
Warning: Tiller is already installed in the cluster.

% helm install --name etcd-operator stable/etcd-operator --namespace compose
Error: a release named etcd-operator already exists.
Run: helm ls --all etcd-operator; to check the status of the release
Or run: helm del --purge etcd-operator; to delete it

% kubectl apply -f compose-etcd.yaml
etcdcluster.etcd.database.coreos.com "compose-etcd" configured

% kubectl create clusterrolebinding <ACCOUNT>-cluster-admin-binding --clusterrole=cluster-admin --user=<ACCOUNT>
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "<ACCOUNT>-cluster-admin-binding" already exists

% ./installer-darwin -namespace=compose -etcd-servers=http://compose-etcd-client:2379 -tag=v0.4.18
INFO[0000] Checking installation state
INFO[0000] Compose version v0.4.18 is already installed in namespace "compose" with the same settings
```

After that run deploy.

```
% cli/build/docker-darwin-amd64 stack deploy -c compose-on-k8s.yml --orchestrator=kubernetes mycluster
failed to find a Stack API version
```

Docker CLI version

```
% cli/build/docker-darwin-amd64 version 
Client:
 Version:           19.09.0-dev
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        0f337f1
 Built:             Wed May 29 07:55:36 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

I cannot find compose api

```
% kubectl api-versions | grep compose
```

**Comment by mvanmeerbeck** [comment]
+1 same problem but with minikube

**Comment by GitHub30** [comment]
+1 same problem but with minikube

**Comment by masayuki14** [comment]
Does anyone have a good idea?

**Comment by fscamuzzi2** [comment]
same here!!!!

**Comment by awh4kc** [comment]
What happens you run `kubectl get all --namespace compose`

**Comment by stylergergely** [comment]
The same thing here. In my case `kubectl get all --namespace compose` returns the following:
```
NAME                                                                  READY   STATUS    RESTARTS   AGE
pod/compose-etcd-2mmvdj5wqs                                           1/1     Running   0          24m
pod/compose-etcd-g77spwfhtv                                           1/1     Running   0          23m
pod/compose-etcd-lpf2kbtkq8                                           1/1     Running   0          24m
pod/etcd-operator-etcd-operator-etcd-backup-operator-ddd46947dnl4nk   1/1     Running   0          26m
pod/etcd-operator-etcd-operator-etcd-operator-5db4855dd8-nbtn6        1/1     Running   0          26m
pod/etcd-operator-etcd-operator-etcd-restore-operator-75d7744ckgmh9   1/1     Running   0          26m

NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/compose-etcd            ClusterIP   None           <none>        2379/TCP,2380/TCP   24m
service/compose-etcd-client     ClusterIP   10.X.X.X   <none>        2379/TCP            24m
service/etcd-restore-operator   ClusterIP   10.X.X.X     <none>        19999/TCP           26m

NAME                                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/etcd-operator-etcd-operator-etcd-backup-operator    1/1     1            1           26m
deployment.apps/etcd-operator-etcd-operator-etcd-operator           1/1     1            1           26m
deployment.apps/etcd-operator-etcd-operator-etcd-restore-operator   1/1     1            1           26m

NAME                                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/etcd-operator-etcd-operator-etcd-backup-operator-ddd46947d     1         1         1       26m
replicaset.apps/etcd-operator-etcd-operator-etcd-operator-5db4855dd8           1         1         1       26m
replicaset.apps/etcd-operator-etcd-operator-etcd-restore-operator-75d7744c9c   1         1         1       26m
```

**Comment by alechp** [comment]
Minikube
<img width="1552" alt="Screen Shot 2020-01-03 at 3 13 39 PM" src="https://user-images.githubusercontent.com/3058939/71754597-b2723a00-2e3b-11ea-9623-c30995e1763b.png">
> Comment: I specified 1.16.0 for kubernetes (instead of 1.17.0) because the latest alpha release for compose-on-kubernetes supports 1.16


Kubectl 
<img width="1552" alt="Screen Shot 2020-01-03 at 3 13 05 PM" src="https://user-images.githubusercontent.com/3058939/71754563-9078b780-2e3b-11ea-877f-26e64c5847bb.png">

**Comment by silvin-lubecki** [comment]
@alechp It looks like the compose controller pod has a `CrashLoopBackOff`, can you print the logs/events you have on this pod?

**Comment by phantasia15** [comment]
Encounter the same problem with microk8s & docker-cli 19.03.5. 
I did a bit of tracing and found out that:
- The error message "failed to find a Stack API version" is because docker-cli fails to authenticate with the cluster. The result is an empty list (403 denied) so it cannot find the compose api.
- docker-cli 19.03+ uses `docker context` to manage cluster endpoints instead of directly reading from kubeconfig file. However, `docker context` currently only support auth-provider, not basic auth/token based authentication (only auth-provider)
- microk8s uses basic auth for authentication by default.

I thinks the same thing happens for minikube, but not sure about gcp
My workaround for now is to downgrade docker-cli to 18.09 and everything works ok now.

**Comment by alechp** [comment]
> * docker-cli 19.03+ uses `docker context` to manage cluster endpoints instead of directly reading from kubeconfig file. However, `docker context` currently only support auth-provider, not basic auth/token based authentication (only auth-provider)

> I thinks the same thing happens for minikube, but not sure about gcp
> My workaround for now is to downgrade docker-cli to 18.09 and everything works ok now.

Any idea how to specify docker version for minikube ? I can set the k8s version, but it still defaults to latest docker - even when I downgrade my local CLI to 18.09.2 (on mac)

**Comment by silvin-lubecki** [comment]
@phantasia15  A PR has been opened on docker/cli to fix the auth issue https://github.com/docker/cli/pull/2308 👍

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
