### ISSUE TITLE
Deploy etcd raises error

### ISSUE THREAD

**Issue by cjancsar** [docker/compose-on-kubernetes#114]
When following instructions in https://github.com/docker/compose-on-kubernetes/blob/master/docs/deploy-etcd.md line-by-line, when running the `kubectl apply -f compose-etcd.yaml` command, an error is raised:

`error: unable to recognize "compose-etcd.yaml": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"`

I have looked through many related issues but have not been able to find a solution. Does compose-for-kubernetes work on AWS EKS?

**Comment by simonferquel** [comment]
The EtcdCluster CRD is installed by etcd-operator. Can you confirm that etcd-operator is running on your cluster ? Also what does `kubectl get crd` gives you?

**Comment by cjancsar** [comment]
I have run out of time to work on this and will just need to use `Kompose` instead sorry. Maybe I will get back to this eventually. But will close for now.
