### ISSUE TITLE
Mapping to job?

### ISSUE THREAD

**Issue by denisa** [docker/compose-on-kubernetes#118]
deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

has two very different behavior:
in the docker world, the service is restarted until it completes successfully, then it is left to rest.
in the kubernetes world, the service is constantly restarted, even after it has completed successfully

It seems that the (expected) docker behavior would best be achieved by mapping the service to a Job

**Comment by silvin-lubecki** [comment]
Hello @denisa , thank you for this issue. We have plan about Kubernetes jobs, so yes it may fit with what you propose.

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
