### ISSUE TITLE
"the server has asked for the client to provide credentials"

### ISSUE THREAD

**Issue by alanjds** [docker/compose-on-kubernetes#119]
After following the install instructions and installing an extra etcd cluster, the API got stable up. However, directing any command via `docker stack` gives the answer "the server has asked for the client to provide credentials", even the `kubectl` commands working nicely:

```bash
$ kubectl get services --namespace compose
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
compose-api                   ClusterIP   10.100.84.128    <none>        443/TCP             41m
etcd-restore-operator         ClusterIP   10.100.249.3     <none>        19999/TCP           28h
example-etcd-cluster          ClusterIP   None             <none>        2379/TCP,2380/TCP   45m
example-etcd-cluster-client   ClusterIP   10.100.249.165   <none>        2379/TCP            45m

$ kubectl api-versions | grep compose
compose.docker.com/v1beta1
compose.docker.com/v1beta2

$ kubectl get stacks --namespace compose
No resources found.

$ docker stack deploy --orchestrator kubernetes --namespace compose --compose-file docker-compose-v3.yaml mystackname
the server has asked for the client to provide credentials

$ docker --version
Docker version 19.03.0-rc2, build f97efcc
```

Am I doing something wrong or is `docker stack` doing wrong?

(cc: @henriquegibin, @adelsjnr, @thiagoscherrer)

**Comment by jcsirot** [comment]
Hello @alanjds, thank you for opening the issue. Can you give us more details about the environment on which your kubernetes cluster is running (on-premises? GKE?...)

**Comment by alanjds** [comment]
Sure.

We are evaluating k8s options. This is a Rancher-installed EKS. We let the Rancher do everything it wanted. The authentication is via Github. Then I logged into Rancher and downloaded a generated `~/.kube/config` file.

As you see, every `kubectl` command is working, so I would assume that no auth issue is occurring.

Am I missing something obvious? I have no previous experience with k8s, only with docker-compose.

**Comment by Alrexxar** [comment]
@alanjds I got the same problem and i think the issue may arise due to RBAC and the lack of a service account
Have you found a solution in the meantime?

**Comment by alanjds** [comment]
We settled to use https://github.com/kubernetes/kompose instead on my team. All the transformation occurs on a dev/ci-cd machine and we can do transformations on the output .yaml before applying.

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
