### ISSUE TITLE
Install on Azure AKS guide: Adjust etcd server URL when using TLS

### ISSUE THREAD

**Issue by ArneMancofi** [docker/compose-on-kubernetes#123]
In the subsection [Compose on Kubernetes](https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-aks.md#deploy-compose-on-kubernetes) of the [Installation on Azure AKS guide](https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-aks.md), it seems that the installer command
```
installer-[darwin|linux|windows.exe] ... -etcd-servers=http://compose-etcd-client:2379 ...
```
should be tweaked when using Mutual TLS into something like
```
installer-[darwin|linux|windows.exe] ... -etcd-servers=https://compose-etcd-client:2379 ...
```
(i.e., `https` instead of `http`), right?

Also, it seems vital that the server certificates used for setting etcd up with mutual TLS, as indicated in the [Deploy etcd guide, Option 2](https://github.com/docker/compose-on-kubernetes/blob/master/docs/deploy-etcd.md#option-2-create-a-secure-and-highly-available-etcd-cluster), must contain the name given above as argument to `--etcd-servers=`, right? Currently, the guide just says it must contain `compose-etcd.compose.svc`, not `compose-etcd-client`.

I suggest adjusting the two guides to clarify these points.

As an aside, debugging compose-api when misconfigured with HTTP instead of HTTPS was not easy, as the log messages did not indicate any such misconfiguration.

**Comment by silvin-lubecki** [comment]
Hello @ArneMancofi thank you for filling this issue 👍 
Do you feel confident with opening a PR to modify the guides?

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
