### ISSUE TITLE
k8s 1.16: serialization issue, namespace deletion hangs

### ISSUE THREAD

**Issue by guillaumerose** [docker/compose-on-kubernetes#150]
Yesterday, I tried to integrate compose-on-kubernetes v0.4.24 in Docker Desktop but faced one strange issue. It's not triggered when using kind in the CI here.

Steps:
1. Install Docker Desktop with Kubernetes 1.16 - https://download-stage.docker.com/mac/edge/39313/Docker.dmg
2. Enable Kubernetes
3. `kubectl create ns redis`
4. `kubectl delete ns redis` hangs forever.

kube-controller log shows plenty of:
```
E1010 09:32:12.184709       1 namespace_controller.go:148] deletion of namespace redis failed: object *v1alpha3.StackList does not implement the protobuf marshalling interface and cannot be encoded to a protobuf message
```

kube-compose-apiserver logs:
```
E1010 09:32:27.861111       1 writers.go:172] apiserver was unable to write a JSON response: object *v1alpha3.StackList does not implement the protobuf marshalling interface and cannot be encoded to a protobuf message
```

Nothing special in kube-apiserver logs.

**Comment by chris-crone** [comment]
It appears that while all other requests to the Compose API Server use JSON, delete collection (which is called as part of delete namespace) always uses protobuf – even if we register the API Server as only having JSON and YAML support. I think this is a Kubernetes 1.16 bug and we are looking for a work around.
