### ISSUE TITLE
The installer CLI properties use single dash instead doubles dashes

### ISSUE THREAD

**Issue by ghost** [docker/compose-on-kubernetes#151]
The GKE documentation shows the following:
```
Run installer-[darwin|linux|windows.exe] -namespace=compose -etcd-servers=http://compose-etcd-client:2379
```
While it's true that the Darwin installer for example shows single dashes in the usage instructions, but single dashes will eventually cause the installation fail in GKE. Double dashes work though:
```
Run installer-[darwin|linux|windows.exe] --namespace=compose --etcd-servers=http://compose-etcd-client:2379
```

**Comment by silvin-lubecki** [comment]
Hello @Fogetti , thank you for reporting this issue 👍 
While we obviously can update this, we think it's better if the PR comes from the community.
Do you think you can create a PR to fix it? If you need any help feel free to reach us!

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
