### ISSUE TITLE
Deploying Helm Charts using docker-compose

### ISSUE THREAD

**Issue by jessechahal** [docker/compose-on-kubernetes#154]
I was reading [https://www.docker.com/blog/simplifying-kubernetes-with-docker-compose-and-friends/](https://www.docker.com/blog/simplifying-kubernetes-with-docker-compose-and-friends/)

> We already have some thoughts about a Helm plugin to make describing your application with Compose and deploying with Helm as easy as possible.

I haven't seen any issues, documentation, or examples in this repo talking about deploying helm charts with docker-compose so I thought I would create a new one here. Is there any information about this helm plugin?

**Comment by justincormack** [comment]
Hi, we did an experimental Helm v2 plugin. We recently did start some very early experiments with Helm v3 but not sure what state it is in. I would recommend opening an issue on https://github.com/docker/roadmap rather than here.

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
