### ISSUE TITLE
Can't use NodePort with minikube "bare metal"

### ISSUE THREAD

**Issue by natehaze** [docker/compose-on-kubernetes#155]
Short story.  Minikube without a vm driver uses a load balancer which does NOT map to the external IP of the minikube/docker host.  It seems that minikube tunnel is supposed to help with this, but it does not seem to work in a 'bare metal' environment.  The service created by compose on kubernetes is therefore not accessible on the **host** by the published port (5100), only the random NodePort (30642 in this case).

_compose:_
```
      - target: 5000
        published: 5100
        protocol: tcp
        mode: host
```
_kubectl get:_
`service/x-published   LoadBalancer   10.103.34.126    <pending>     5100:30642/TCP   103s`

Using a nodeport instead of a loadbalancer does seem to work for a simple hello world example.  In reading the documentation for compose on k8, at https://github.com/docker/compose-on-kubernetes/blob/master/docs/mapping.md, it looks like there should be an option to the controller of `--default-service-type=NodePort`.  In this case the NodePort would use the published port by default.

However, I can find NO way of actually applying that option to the compose controller.  It isn't an option to the install script, and it seems that the install script is the only thing that propagates options to the controller.

**Is there a way to set this?**  Also, I don't know exactly how this would work and if an external IP is going to be necessary.  Is it possible to set the external IP to the host IP?

**Comment by huuhait** [comment]
up

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
