### ISSUE TITLE
etcd install instructions outdated

### ISSUE THREAD

**Issue by alechp** [docker/compose-on-kubernetes#156]
**Error**
> <img width="416" alt="Screen Shot 2019-12-18 at 1 30 24 PM" src="https://user-images.githubusercontent.com/3058939/71124829-906d8c00-219a-11ea-8d94-96f38455359a.png">

```
helm init --service-account tiller
Error: unknown flag: --service-account
```

**Reason for Error** 
> helm init is included in the etcd install instructions
> https://github.com/docker/compose-on-kubernetes/blob/master/docs/deploy-etcd.md
> <img width="843" alt="Screen Shot 2019-12-18 at 1 28 01 PM" src="https://user-images.githubusercontent.com/3058939/71124677-3cfb3e00-219a-11ea-9d55-4b957f876250.png">

**Reference**
> https://github.com/helm/helm/issues/7052#issuecomment-557554311
![image](https://user-images.githubusercontent.com/3058939/71124736-5bf9d000-219a-11ea-822b-a0c593891a8b.png)

PS. Created an issue instead of a PR because I'm not sure what versions this tutorial is targeting

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
