### ISSUE TITLE
compose-on-kubernetes is removed from Docker Desktop

### ISSUE THREAD

**Issue by DonnyVerduijn** [docker/compose-on-kubernetes#164]
Please note that since Docker Desktop 2.3.3.0 compose-on-kubernetes needs to be installed separately. The Readme should be updated accordingly.

**Comment by chris-crone** [comment]
Hi @DonnyVerduijn,

Do you mean the README on this repo or for Desktop?

On this repo, we had a PR to update the README but hadn't merged it yet. It's [now merged](https://github.com/docker/compose-on-kubernetes#install-compose-on-kubernetes-on-docker-desktop).

**Comment by DonnyVerduijn** [comment]
Nvm, didn't notice the pull request.
