### ISSUE TITLE
the server is currently unable to handle the request (get stacks.compose.docker.com)

### ISSUE THREAD

**Issue by cclauss** [docker/compose-on-kubernetes#172]
How should I resolve the following error on Docker Desktop Mac?

% `docker stack ls`
```
the server is currently unable to handle the request (get stacks.compose.docker.com)
```
I installed yesterday everything was working smoothly.  I even did a few example projects including wordsmith.

Then I rebooted.  ;-(  Now I get this error and do not know how to debug.

% `kubectl api-versions | grep compose`
```
compose.docker.com/v1alpha3
compose.docker.com/v1beta1
compose.docker.com/v1beta2
```

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
