### ISSUE TITLE
Feature request: Ingress resources

### ISSUE THREAD

**Issue by kinghuang** [docker/compose-on-kubernetes#40]
I'm experimenting with deploying existing Swarm stacks to Kubernetes via the Compose on Kubernetes controller. On Docker Swarm, the services are using Traefik for http/https ingress, configured with labels on Swarm services. Is there some way to adapt this to Ingress resources on Kubernetes via the Compose controller?

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
