### ISSUE TITLE
Add tests to the installer code

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#45]
Currently, the installer is not tested at all (except the parts used for e2e test environment deployment).

We need to improve our confidence in the installer, and thus require a bunch of unit tests and e2e tests (tests with custom TLS bundle, various ETCD configurations, ...)

**Comment by waveywaves** [comment]
@simonferquel I want ot take this up. Is there anything in particular I should keep in mind before starting work on this issue.

**Comment by simonferquel** [comment]
@waveywaves Thanks a lot for proposing this. There are 2 categories of tests we'd like to have:
- Unit tests using kubernetes Fakes:
  - validate that the installer creates the required entities for any given set of options (a huge matrix here, this might need some priorization)
  - validate the installation state detection and the logic behind deciding to re-deploy or not given a previous state, and a new set of installation parameters (I am almost certain there are bugs lurking there)
- e2e tests using Kind
  - Validation against a broad set of deployment parameters (etcd with TLS, external mutual TLS bundles, different defaultServiceTypes etc.)

**Comment by waveywaves** [comment]
Okay, I will work on these given points. Thank you @simonferquel

**Comment by waveywaves** [comment]
@simonferquel I have started work on this. Please do assign this issue to me.

**Comment by simonferquel** [comment]
For some reason github refuses to assign it to you. I'll assign it to myself in the mean time then, to makes sure no one else works on it.
Also, please open a WIP Pull Request so that we can see progress / provide early feedback.
