### ISSUE TITLE
Prepare v0.4.18

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#47]
We are about to tag before merging v1alpha3.
We need first to update docs as the --skip-livenessprobes won't be needed anymore

**Comment by chris-crone** [comment]
I agree with @collabnix, it would be good to document that you need an as yet unreleased Docker CLI for GKE.

I think the best place would be in a guide for GKE (like the ones we have for [AKS](https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-aks.md) and [Minikube](https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-minikube.md)).

**Comment by simonferquel** [comment]
v0.4.18 is done, closing
