### ISSUE TITLE
Document installation on other managed clusters

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#51]
We currently have documentation for installing on Minikube and Azure AKS.
We should also document the installation on:
- ~~Google GKE~~
- Amazon EKS
- Kubernetes on Amazon AWS
- Play with Kubernetes
- Kind (Kubernetes in Docker)
- Digital Ocean
- Alibaba Cloud (**Help wanted**)
- [ insert your favorite k8s environment here ]

Based on the existing documentation, this should be straight forward.

**Comment by denisa** [comment]
Alicloud, please.

**Comment by cjancsar** [comment]
AWS?

**Comment by silvin-lubecki** [comment]
Hello @denisa and @cjancsar, help is welcome here to improve the documentation 😺 
The installation procedure should look like [the GKE one](https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-gke.md), but with a different administration section.
Feel free to open a PR on the docs, or ask for help to write it 👍

**Comment by cjancsar** [comment]
@silvin-lubecki I can add docs for it, however I spent about 4-6 hours on this yesterday and am about ready to move on to just using `Kompose` as it isn't very straight forward.

I got to adding `heml` and the `etcd-operator` but I could not bring up a etcd cluster so things failed after that.

Please let me know if you can point me in the right direction and I will try to modify my approach. I have a feeling it could be related to all the RBAC stuff, but don't have a clear picture of what is required for that.

**Comment by ilyakaznacheev** [comment]
Probably should add [Mail.ru Cloud](https://mcs.mail.ru/containers/) and [Yandex Cloud](https://cloud.yandex.ru/services/managed-kubernetes) into the list.
