### ISSUE TITLE
PerssitentVolume enhancement

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#57]
Our current persistent volume support lacks some important features. Mainly we need support for:
- configurable size
- configurable storage class
- configurable mode 
- provisioner-specific options

For this, we'll need to introduce a root-level volume-list in the stack spec so that we can populate those options easily (instead of treating all volume mounts as default-100MB volumes)

**Comment by MBARIMike** [comment]
How about also interpolating variables from .env file settings?

**Comment by xgeraldx** [comment]
I still cannot fine how to define the persistent volumes in a compose file....I created the claims already in K8s, with the same names in the compose file. When the stack is created it still creates the persistent volume claims with all the defaults. How can I change the storage size as well as the persistent volume name? Thanks in advance.

**Comment by tubbo** [comment]
> instead of treating all volume mounts as default-100MB volumes

This completely shits the bed on DigitalOcean since they require 1GB volume mounts as a minimum. All PVCs fail when trying to deploy.
