### ISSUE TITLE
[Networking] Use ClusterIP when possible

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#64]
# Context
Today, Compose on Kubernetes creates Headless Services to enable Service to Service communication. This 
brings the same developer experience as when working with `docker-compose` or `swarm`, but it is not always the best option. We should prefer creating ClusterIP if we get enough information about how to configure it properly.

## Headless service pros
- No KubeProxy involved: direct POD to POD communication means less latency, less load on the kube-proxy component
- Do not require a list of exposed port: As there is no proxy involved, a headless service alows to reach any port opened by a POD

## Headless service cons
- No real load balancing: the DNS server only answers with as many records as there are PODs matching its selector. It is the responsibility of the client network stack to decide if it should do some round-robin on those DNS entries. Many development runtime don't do that, and worse than that, some just take the first entry into account
- Scalability issue: depending on DNS caching policy on the client, its knowledge of the valid PODs IP can be stale. Worse, some network client stacks have a very aggressive DNS caching policy, and never re-query the DNS server: those can become stuck trying to reach PODs that have been unscheduled due to a change in service scaling.

## Potential solution
Introduce the option to use ClusterIP services instead of headless using this strategy:
- introduce a field on ServiceConfig named `InternalServiceType` that can be `Headless` or `ClusterIP`
- introduce a default behavior, that looks for the `Expose` field in ServiceConfig (see https://docs.docker.com/compose/compose-file/#expose): if it is empty, defaults to Headless. Else use ClusterIP

ClusterIP ports configuration will use the `Expose` field in the ServiceConfig to decide which ports to route.

**Comment by phng** [comment]
I looked at the PR and it seems there are 2 new properties can be set `InternalPorts` and `InternalServiceType`. How do I go about using these as they are not valid compose file property?

**Comment by silvin-lubecki** [comment]
Hello @phng , this feature was introduced in the `docker/cli` with this PR https://github.com/docker/cli/pull/1815/files#diff-b3114871e359bbcd13674fefe7b3e16eR30 and then refactored on this PR https://github.com/docker/cli/pull/1823 .

To summarize, you can use this feature in your compose file adding 
```yaml
services:
  test:
    image: "some-image"
    x-kubernetes:
      internal-service-type: {"Headless"|"ClusterIP"}
```
This feature is available with the latest 19.03 docker cli (should be shortly released), and is experimental (as there is a `x-` prefix). We definitely need some feedbacks about this feature so please try it 👍

**Comment by phng** [comment]
@silvin-lubecki Thanks for the instructions. 

I added
```
mdm:
    image: mdm
    build:
      context: ../server
      dockerfile: Dockerfile
    env_file:
      - mdm.env
    deploy:
      replicas: 2
    x-kubernetes:
      internal-service-type: ClusterIP
```
However, the service created is still a headless headless service.

```
kubectl describe service mdm
Name:              mdm
Namespace:         default
Labels:            com.docker.service.id=rrts-mdm
                   com.docker.service.name=mdm
                   com.docker.stack.namespace=rrts
Annotations:       <none>
Selector:          com.docker.service.id=rrts-mdm,com.docker.service.name=mdm,com.docker.stack.namespace=rrts
Type:              ClusterIP
IP:                None
Port:              headless  55555/TCP
TargetPort:        55555/TCP
Endpoints:         10.1.0.104:55555,10.1.0.107:55555
Session Affinity:  None
Events:            <none>
```

**Comment by phng** [comment]
It looks like my Docker Desktop kubernetes version is 1.14.3, and stack api version is v1beta2. How do I upgrade the server version to v1alpha3? Or do I have to wait for the new release in edge channel?
