### ISSUE TITLE
Stack Status: more details

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#66]
Currently, the stack status is very limited in term of information it brings (just the reconciliation phase an a single error message)

We'd like to show more informations there:
- Details about each service:
  - Link to every created child resource
  - Copy of Child Resources status
- Scale information (similar to the scale subresource)
- TBD

**Comment by philipz** [comment]
scale +1

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
