### ISSUE TITLE
Replace testkit with Kind, and test on Kubernetes v1.13

### ISSUE THREAD

**Issue by simonferquel** [docker/compose-on-kubernetes#67]
Originally we used to run e2e tests with Testkit, an internal tool at Docker to create cluster.
We have recently moved to Kind for testing PRs, and as the current in-dev branch will only be deployed in Docker products based on Kubernetes 1.11+, we can now remove all things related to testkit from the master branch, and use Kind everywhere. (we'll keep testkit config files on our CI environment to be able to build older 1.10+ branches if required)

Additionally we need to run our e2e suite on Kubernetes 1.11, 1.12 and 1.13, and we need to re-establish a baseline for our benchmark to avoid false-positives.

**Comment by jcsirot** [comment]
Partially done in #74
