### ISSUE TITLE
Be able to choose the healthcheck api-server port

### ISSUE THREAD

**Issue by guillaumerose** [docker/compose-on-kubernetes#70]
Currently in Docker Desktop, we deploy Compose on Kubernetes with option `--network-host=true` so that we can reuse the same etcd as Kubernetes core API.

The default port for api-server is 8080 which collides with containers deployed by hand by users.

Steps:
1. Activate Kubernetes in Docker Desktop
2. `docker run -p 8080:80 -it nginx`

Output: `Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.`

When doing netstat inside the VM: `tcp        0      0 :::8080                 :::*                    LISTEN      8655/api-server` 

Is it possible to add a flag for this port in order to use a non-usual port and let 8080 free for our users ?

**Comment by simonferquel** [comment]
Hmm, actually it is the HealthCheck port. We should add a flag in API server to disable the HealthCheck listener (currently the --skip-healthchecks install flag only skip the declaration in the pod template), and another to change the healthcheck port (and surface this flag to the installer as well).

Thanks for the feedback!

**Comment by djs55** [comment]
This would be the root cause of https://github.com/docker/for-mac/issues/3522 . I've also filed https://docker.atlassian.net/browse/DD-719

**Comment by djs55** [comment]
There used to be a solution in Desktop to avoid this kind of problem -- we would avoid binding in the VM to avoid clashes there: https://github.com/moby/vpnkit/commit/4f21cb2e40f510f21f9971d06f4be72dd1ac0c14 . I think we lost  it at some point in the past.
