### ISSUE TITLE
Overlap with kompose

### ISSUE THREAD

**Issue by rasmusskovdk** [docker/compose-on-kubernetes#79]
How does this initiative differ from https://github.com/kubernetes/kompose?
Seems very alike.

**Comment by simonferquel** [comment]
The key difference with Kompose, is that Kompose is a client-side "one-shot" conversion tool, while compose-on-kubernetes approach is to bring a new server-side Kubernetes resource called "Stack" which is reconciled into lower level Kubernetes resources (the same way Kubernetes reconciles Deployments into Replicasets).

This allows interesting stack-level operation like:
- stack-level monitoring (status aggregation, logs aggregation...)
- stack-level actions (scaling)
- ability to modify the stack definition (and having the reconciler do the correct operation: delete/create new deployments while keeping unmodified parts alive...)
- atomic lifetime: deleting a stack resource triggers deletion of all the underlying deployments, services, volume claims etc.

This comes at the cost of having to deploy server-side workloads though, so I guess both tools have their place in the ecosystem.
