### ISSUE TITLE
etcd dependency

### ISSUE THREAD

**Issue by kfox1111** [docker/compose-on-kubernetes#98]
Why store all the state in an etcd? You could store the state back into k8s via crd specifically for compose-on-kubernetes. This would make compose-on-kubernetes totally stateless and thus, easier to manage.

**Comment by chris-crone** [comment]
Compose on Kubernetes used to be a CRD but we moved to an API server to provide a better UX. Specifically with older versions of Kubernetes, you couldn't do much (any?) validation of payloads. This meant that all errors appear in the reconciliation loop rather than synchronously when the user tried to do something.

Shameless plug: I did a [talk about exactly this at DockerCon EU 2018](https://www.youtube.com/watch?v=pCXFhCfOAIg).

**Comment by simonferquel** [comment]
Once we support only versions of kubernetes suporting CRD subresources and conversion webhooks (as well as admission and mutating webhooks), I'd love for us to move back to a CRD for easier deployment. We'll need to provide a data-conversion tool in the process then, but I aggree with you @kfox1111, that would be awesome :)

**Comment by simonferquel** [comment]
(for context, see https://github.com/kubernetes/enhancements/issues/598)

**Comment by kfox1111** [comment]
ah. gotcha.

Could the storage be abstracted so that crd and etcd could be co-supported so that those that already have enough functionality in the Kubernetes cluster can use the stateless version, and those that are on older clusters can use the stateful one? Wouldn't a validation webhook be enough? Maybe supporting both is too much work though.

**Comment by simonferquel** [comment]
Problem is, conversion webhooks are not there yet, even in 1.14 (beta is planned for 1.15). It might not be too much of a problem with v1beta2 and v1alpha3, but it is a serious issue for supporting v1beta1 which is how the docker Enterprise UI talks to compose on Kubernetes as of today.

**Comment by ArneMancofi** [comment]
The [etcd operator project](https://github.com/coreos/etcd-operator) is no longer actively developed or maintained. Shouldn't compose-on-kubernetes then move away from etcdop now?

**Comment by chris-crone** [comment]
Hi! Thanks for your feedback. Unfortunately we're no longer maintaining this repository so I will close this issue.
